import { ToDoObj } from "../engine/toDoEngine";
export declare const VAPID_PUB_KEY = "BFeFiK9dB7L-JJqRrql83EdAIQ3MOlaHaQYKlM_AZ3m4dSIGNxQy5_Wdthd7_IP-U8wZEyJl4e5gheTsR4ys78o";
export declare function generateLicenseKey(): string;
export declare function delay(ms: number): Promise<void>;
export declare function getDeviceId(): Promise<string>;
export declare function hashPassword(password: string): Promise<Uint8Array>;
export declare const SW_BROADCAST_CHANNEL = "service_worker_channel";
export declare function formatDate(d: Date): string;
export declare function parseStringToDate(dateString: string): Date;
export declare function minToParsedTime(min: number): string;
export declare function isToday(date: Date): boolean;
export declare function parseActionDates(action: ToDoObj): void;
